#!/usr/bin/env bash
set -euo pipefail

RUN_CMD="$1"
BIN_URL="$2"
BIN_REF="$3"
IMAGE="$4"

cat <<EOF > github.env
GITHUB_SHA=$GITHUB_SHA
GITHUB_REF=$GITHUB_REF
GITHUB_REF_NAME=$GITHUB_REF_NAME
GITHUB_RUN_ID=$GITHUB_RUN_ID
GITHUB_REPOSITORY=$GITHUB_REPOSITORY
GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME
GITHUB_ACTOR=$GITHUB_ACTOR
GITHUB_TOKEN=$GITHUB_TOKEN
CIBUILDER_BIN_URL=$BIN_URL
CIBUILDER_BIN_REF=$BIN_REF
CIBUILD_RUN_CMD=$RUN_CMD
CIBUILD_CI_TOKEN=$CIBUILD_CI_TOKEN
CIBUILD_BASE_REGISTRY_PASS=$CIBUILD_BASE_REGISTRY_PASS
CIBUILD_TARGET_REGISTRY_PASS=$CIBUILD_TARGET_REGISTRY_PASS
CIBUILD_BUILD_BUILDKIT_CLIENT_KEY=$CIBUILD_BUILD_BUILDKIT_CLIENT_KEY
CIBUILD_BUILD_BUILDKIT_SERVICE_ACCOUNT=$CIBUILD_BUILD_BUILDKIT_SERVICE_ACCOUNT
CIBUILD_TEST_SERVICE_ACCOUNT=$CIBUILD_TEST_SERVICE_ACCOUNT
CIBUILD_RELEASE_COSIGN_PRIVATE_KEY=$CIBUILD_RELEASE_COSIGN_PRIVATE_KEY
EOF

docker network create cibuilder-net

docker network inspect cibuilder-net

docker run --privileged --rm -d \
  -e DOCKER_HOST=tcp://0.0.0.0:2375 \
  -e DOCKER_TLS_VERIFY= \
  -e DOCKER_TLS_CERTDIR= \
  --network cibuilder-net \
  --network-alias docker \
  --name cibuilder-dind \
  docker:dind

docker run --privileged --rm \
  --env-file github.env \
  -v "$PWD:/workspace" \
  -w /workspace \
  --network cibuilder-net \
  --name cibuilder \
  "$IMAGE"
